name: Build

on:
  push:
  pull_request:
  release:
    types: [published]

env:
  GHIDRA_VERSION: "10.2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "19.0.1"
        cache: "gradle"

    - uses: er28-0652/setup-ghidra@0.0.6
      with:
        version: ${{ env.GHIDRA_VERSION }}

    - name: Setup Gradle and build efiSeek
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
  
    - name: Upload release
      if: ${{ github.event_name == 'release' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.zip
        file_glob: true
        tag: ${{ github.ref }}
