on: [push, pull_request]

env:
  LOG_PATH: example/analysis.log
  REPORT_PATH: example/analysis.xml

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout efiSeek
      uses: actions/checkout@v2
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate JUnit XML reports
      run: python scripts/gen_report.py ${{ env.LOG_PATH }} ${{ env.REPORT_PATH }}
    - name: Publish JUnit test results
      uses: EnricoMi/publish-unit-test-result-action@v1.36
      with:
        files: ${{ env.REPORT_PATH }}
